#!/bin/bash
dhcpcd
sed -n '/%wheel ALL=(ALL) ALL /s/^#//' /etc/sudoers
echo "server de.pool.ntp.org" >> /etc/ntp.conf
ntpd -gq
hwclock -w
curl https://raw.githubusercontent.com/jonathankoehn/alic/master/servicesToEnable > servicesToEnable
for service in $(<servicesToEnable); do
  systemctl enable ${service}
done
curl https://raw.githubusercontent.com/jonathankoehn/alic/master/sshd_config > /etc/ssh/sshd_config
read -p "Enter username: " username
useradd -m -g users -s /bin/bash $username
passwd $username
gpasswd -a $username wheel
echo "AllowUsers $username" >> /etc/ssh/sshd_config
curl https://raw.githubusercontent.com/jonathankoehn/alic/master/conkyscript > /home/${username}/conkyscript
curl https://raw.githubusercontent.com/jonathankoehn/alic/master/conkyrcL > /home/${username}/.conkyrc
curl https://raw.githubusercontent.com/jonathankoehn/alic/master/conkyrcRO > /home/${username}/.conkyrcRO
curl https://raw.githubusercontent.com/jonathankoehn/alic/master/conkyrcRU > /home/${username}/.conkyrcRU
rm installScript2
rm configScript
rm servicesToEnable
