#!/bin/bash
pacman -S sudo ntp acpid dbus avahi cups cronie xorg-server xorg-xinit  xorg-utils xorg-server-utils xorg-drivers ttf-dejavu networkmanager grub gnome gnome-extra network-manager-applet firefox guake openssh conky
read -p "Enter hostname: " hname
echo "$hname" > /etc/hostname
echo KEYMAP=de-latin1 > /etc/vconsole.conf
ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime
echo "de_DE.UTF-8 UTF-8" > /etc/locale.gen
echo "de_DE ISO-8859-1" >> /etc/locale.gen
echo "de_DE@euro ISO-8859-15" >> /etc/locale.gen
locale-gen
mkinitcpio -p linux
passwd 
grub-mkconfig -o /boot/grub/grub.cfg
grub-install /dev/sda
curl https://raw.githubusercontent.com/jonathankoehn/alic/master/configScript > configScript
chmod +x configScript
exit
umount /dev/sda1
reboot
