#!/bin/bash

mkfs.ext4 -L arch /dev/sda1
mkswap -L swap /dev/sda2
mount -L arch /mnt
swapon -L swap

for server in $(<serverlist); do
  echo ${server} >> /etc/pacman.d/mirrorlist
done

pacstrap /mnt base base-devel

genfstab -Lp /mnt > /mnt/etc/fstab
arch-chroot /mnt/

pacman -S sudo ntp acpid dbus avahi cups cronie xorg-server xorg-init  xorg-utils xorg-server-utils xorg-drivers ttf-dejavu networkmanager grub gnome gnome-extra network-manager-applet firefox guake openssh conky

# hostname
read -p "Enter hostname: " hname
echo "$hname" > /etc/hostname

echo KEYMAP=de-latin1 > /etc/vconsole.conf

ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime

echo "de_DE.UTF-8 UTF-8" > /etc/locale.gen
echo "de_DE ISO-8859-1" >> /etc/locale.gen
echo "de_DE@euro ISO-8859-15" >> /etc/locale.gen
locale-gen

mkinitcpio -p linux

passwd 

grub-mkconfig -o /boot/grub/grub.cfg
grub-install /dev/sda

curl -o configScript https://github.com/jonathankoehn/alic
chmod +x configScript

exit
umount /dev/sda1
reboot
